import {StyleSheet} from 'react-native';

export default styles = StyleSheet.create({
  butons: {
    width: '70%',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  textButonAccept: {
    color: '#fff',
    fontFamily: 'Nunito-Regular',
    fontSize: 20,
    alignSelf: 'center',
  },
  textButonClose: {
    color: '#D10E29',
    fontFamily: 'Nunito-Regular',
    fontSize: 20,
    alignSelf: 'center',
  },
  butonCancel: {
    height: 50,
    width: '100%',
    borderRadius: 50,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#D10E29',
  },
  butonAcept: {
    backgroundColor: '#519918',
    height: 50,
    width: '70%',
    borderRadius: 50,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  butonRemove: {
    backgroundColor: '#D10E29',
    height: 50,
    width: '100%',
    borderRadius: 50,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  modalContainer: {
    backgroundColor: '#ffffff75',
    flex: 1,
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingTop: 70,
  },
  textTitle: {
    color: '#484D55',
    fontFamily: 'Nunito-Regular',
    fontSize: 25,
    marginTop: 10,
    alignSelf: 'center',
    textAlign: 'center',
  },
  Input: {
    backgroundColor: '#EDF6FF',
    height: 50,
    width: 300,
    borderRadius: 50,
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  form: {
    alignItems: 'center',
    width: '100%',
    alignSelf: 'center',
  },
  textSubTitle: {
    textAlign: 'center',
    color: '#484D55',
    fontFamily: 'Nunito-Regular',
    fontSize: 15,
    marginHorizontal: 30,
    marginTop: 10,
    marginBottom: 10,
  },
  textWarning: {
    textAlign: 'center',
    color: 'red',
    fontFamily: 'Nunito-Regular',
    fontSize: 15,
    marginHorizontal: 30,
    marginBottom: 10,
  },
  contactEnabled: {
    margin: 10,
    alignSelf: 'center',
    borderColor: '#519918',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    flexDirection: 'column',
  },
  contactEnabledContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  textContactEnabled: {
    padding: 10,
    paddingHorizontal: 20,
    color: '#519918',
  },
  iconView: {
    alignSelf: 'center',
    backgroundColor: 'red',
    flexDirection: 'column',
    width: 40,
    height: 40,
  },
});
