import {StyleSheet} from 'react-native';

export default styles = StyleSheet.create({
  buttons: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  textButtonAdd: {
    color: '#519918',
    fontFamily: 'Nunito-Regular',
    fontSize: 20,
    marginHorizontal: 20,
    alignSelf: 'center',
  },
  textButtonClose: {
    color: '#FF4646',
  },
  textButtonSave: {
    color: 'white',
    fontFamily: 'Nunito-Regular',
    fontSize: 20,
    alignSelf: 'center',
  },
  buttonCancel: {
    color: '#FF4646',
    width: '40%',
    margin: 5,
  },
  buttonAdd: {
    height: '100%',
    width: '100%',
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#2343A9',
    flexDirection: 'row',
  },
  buttonSave: {
    backgroundColor: '#2343A9',
    height: 50,
    width: '40%',
    borderRadius: 50,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    margin: 5,
  },
  modalContainer: {
    width: '100%',
    height: '100%',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  textTitle: {
    color: '#484D55',
    fontFamily: 'Nunito-Regular',
    fontSize: 25,
    marginTop: 10,
    alignSelf: 'center',
    textAlign: 'center',
  },
  Input: {
    backgroundColor: '#EDF6FF',
    width: '80%',
    height: '100%',
    borderBottomLeftRadius: 50,
    borderTopLeftRadius: 50,
    paddingHorizontal: 20,
  },
  form: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  textSubTitle: {
    textAlign: 'center',
    color: '#484D55',
    fontFamily: 'Nunito-Regular',
    fontSize: 15,
    marginHorizontal: 30,
    marginTop: 10,
    marginBottom: 10,
  },
  textWarning: {
    textAlign: 'center',
    color: 'red',
    fontFamily: 'Nunito-Regular',
    fontSize: 15,
    marginHorizontal: 30,
    marginBottom: 10,
  },
  contactEnabled: {
    margin: 10,
    alignSelf: 'center',
    borderColor: '#519918',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    flexDirection: 'column',
  },
  contactContainer: {
    aspectRatio: 10 / 2,
    width: '80%',
    height: undefined,
    flexDirection: 'row',
    alignItems: 'center',
    margin: '10%',
  },
  textContactEnabled: {
    padding: 10,
    paddingHorizontal: 20,
    color: '#519918',
  },
  iconView: {
    backgroundColor: 'red',
    alignSelf: 'center',
    flexDirection: 'column',
    width: '20%',
    aspectRatio: 1,
    borderBottomRightRadius: 50,
    borderTopRightRadius: 50,
    borderRadius: 0,
  },
});
